from __future__ import annotations

CORE_SECTIONS = {
    "Data Operations": [
        "basics-getting-started",
        "data-import-export",
        "data-management",
        "variables-operators",
        "string-functions",
        "date-time-functions",
        "mathematical-functions",
    ],
    "Statistics and Econometrics": [
        "descriptive-statistics",
        "linear-regression",
        "panel-data",
        "time-series",
        "limited-dependent-variables",
        "bootstrap-simulation",
        "survey-data-analysis",
        "missing-data-handling",
        "maximum-likelihood",
        "gmm-estimation",
    ],
    "Causal Inference": [
        "difference-in-differences",
        "regression-discontinuity",
        "matching-methods",
        "treatment-effects",
        "sample-selection",
    ],
    "Advanced Methods": [
        "survival-analysis",
        "sem-factor-analysis",
        "nonparametric-methods",
        "spatial-analysis",
        "machine-learning",
    ],
    "Programming and Mata": [
        "programming-basics",
        "advanced-programming",
        "mata-introduction",
        "mata-matrix-operations",
        "mata-programming",
        "mata-data-access",
    ],
    "Output and Workflow": [
        "graphics",
        "tables-reporting",
        "workflow-best-practices",
        "external-tools-integration",
    ],
}

CORE_SOURCE_TOPICS = {
    "advanced-programming": ["program", "syntax", "return", "ereturn"],
    "basics-getting-started": ["use", "save", "describe", "browse", "sysuse"],
    "bootstrap-simulation": ["bootstrap", "simulate", "permute"],
    "data-import-export": ["import", "import_delimited", "import_excel", "export"],
    "data-management": ["generate", "replace", "merge", "joinby", "duplicates", "isid", "append", "reshape", "collapse", "egen"],
    "date-time-functions": ["datetime", "datetime_translation", "format"],
    "descriptive-statistics": ["summarize", "tabulate", "tabstat", "codebook", "correlate"],
    "difference-in-differences": ["didregress", "xtdidregress"],
    "external-tools-integration": ["python", "shell", "java_plugin"],
    "gmm-estimation": ["gmm"],
    "graphics": ["graph", "twoway", "histogram", "scatter"],
    "limited-dependent-variables": ["logit", "probit", "mlogit", "ologit", "poisson", "nbreg", "tobit"],
    "linear-regression": ["regress", "ivregress", "margins", "predict"],
    "machine-learning": ["lasso", "elasticnet", "dsregress"],
    "mata-data-access": ["mf_st_data", "mf_st_store"],
    "mata-introduction": ["mata"],
    "mata-matrix-operations": ["matrix", "mata"],
    "mata-programming": ["mata", "m2_functions"],
    "matching-methods": ["teffects", "tebalance"],
    "mathematical-functions": ["functions", "random_number_functions"],
    "maximum-likelihood": ["ml"],
    "missing-data-handling": ["mi", "misstable"],
    "nonparametric-methods": ["npregress", "lowess"],
    "panel-data": ["xtset", "xtreg", "xt"],
    "programming-basics": ["foreach", "forvalues", "macro", "do"],
    "regression-discontinuity": ["rd"],
    "sample-selection": ["heckman", "heckprobit"],
    "sem-factor-analysis": ["sem", "gsem", "factor"],
    "spatial-analysis": ["spmatrix", "spregress"],
    "string-functions": ["string_functions", "split", "regexm", "ustrlen"],
    "survey-data-analysis": ["svyset", "svy"],
    "survival-analysis": ["stset", "stcox", "sts"],
    "tables-reporting": ["etable", "collect", "table", "putexcel"],
    "time-series": ["tsset", "arima", "var", "irf"],
    "treatment-effects": ["teffects"],
    "variables-operators": ["datatypes", "missing", "if", "functions"],
    "workflow-best-practices": ["log", "version", "pwd", "cd"],
}

CORE_RELATED_REFS = {
    "advanced-programming": ["programming-basics", "workflow-best-practices"],
    "basics-getting-started": ["data-management", "workflow-best-practices"],
    "bootstrap-simulation": ["linear-regression", "maximum-likelihood"],
    "data-import-export": ["basics-getting-started", "data-management"],
    "data-management": ["variables-operators", "workflow-best-practices"],
    "date-time-functions": ["data-management", "string-functions"],
    "descriptive-statistics": ["linear-regression", "survey-data-analysis"],
    "difference-in-differences": ["panel-data", "treatment-effects"],
    "external-tools-integration": ["workflow-best-practices", "programming-basics"],
    "gmm-estimation": ["maximum-likelihood", "linear-regression"],
    "graphics": ["tables-reporting", "descriptive-statistics"],
    "limited-dependent-variables": ["linear-regression", "maximum-likelihood"],
    "linear-regression": ["descriptive-statistics", "limited-dependent-variables"],
    "machine-learning": ["programming-basics", "workflow-best-practices"],
    "mata-data-access": ["mata-introduction", "mata-programming"],
    "mata-introduction": ["mata-programming", "mata-matrix-operations"],
    "mata-matrix-operations": ["mata-introduction", "mata-programming"],
    "mata-programming": ["mata-introduction", "advanced-programming"],
    "matching-methods": ["treatment-effects", "difference-in-differences"],
    "mathematical-functions": ["variables-operators", "date-time-functions"],
    "maximum-likelihood": ["gmm-estimation", "limited-dependent-variables"],
    "missing-data-handling": ["data-management", "survey-data-analysis"],
    "nonparametric-methods": ["graphics", "machine-learning"],
    "panel-data": ["linear-regression", "difference-in-differences"],
    "programming-basics": ["advanced-programming", "workflow-best-practices"],
    "regression-discontinuity": ["treatment-effects", "difference-in-differences"],
    "sample-selection": ["limited-dependent-variables", "treatment-effects"],
    "sem-factor-analysis": ["maximum-likelihood", "descriptive-statistics"],
    "spatial-analysis": ["graphics", "data-management"],
    "string-functions": ["data-management", "date-time-functions"],
    "survey-data-analysis": ["descriptive-statistics", "missing-data-handling"],
    "survival-analysis": ["limited-dependent-variables", "maximum-likelihood"],
    "tables-reporting": ["graphics", "workflow-best-practices"],
    "time-series": ["panel-data", "graphics"],
    "treatment-effects": ["matching-methods", "difference-in-differences"],
    "variables-operators": ["data-management", "mathematical-functions"],
    "workflow-best-practices": ["basics-getting-started", "programming-basics"],
}

CORE_UPSTREAM_ONLY = {
    "regression-discontinuity",
    "mata-data-access",
    "mata-matrix-operations",
}

PACKAGE_SECTIONS = {
    "Estimation Packages": [
        "binsreg",
        "did",
        "ivreg2",
        "nprobust",
        "psmatch2",
        "rdrobust",
        "reghdfe",
        "synth",
        "xtabond2",
    ],
    "Tables and Reporting": [
        "asdoc",
        "estout",
        "outreg2",
        "tabout",
    ],
    "Graphics and Diagnostics": [
        "coefplot",
        "event-study",
        "graph-schemes",
        "diagnostics",
    ],
    "Data and Workflow Utilities": [
        "data-manipulation",
        "package-management",
        "winsor",
    ],
}

PACKAGE_METADATA = {
    "asdoc": {
        "commands": ["asdoc"],
        "source_topics": ["asdoc"],
        "install_commands": ["ssc install asdoc, replace"],
        "smoke_test": "sysuse auto, clear\nasdoc summarize price mpg, replace",
        "related_refs": ["estout", "outreg2", "tables-reporting"],
    },
    "binsreg": {
        "commands": ["binsreg"],
        "source_topics": ["binsreg"],
        "install_commands": [
            'net install binsreg, from("https://raw.githubusercontent.com/nppackages/binsreg/master/stata") replace'
        ],
        "smoke_test": "sysuse auto, clear\nbinsreg price mpg",
        "related_refs": ["graphics", "nonparametric-methods"],
    },
    "coefplot": {
        "commands": ["coefplot"],
        "source_topics": ["coefplot"],
        "install_commands": ["ssc install coefplot, replace"],
        "smoke_test": "sysuse auto, clear\nreg price mpg weight\ncoefplot",
        "related_refs": ["graphics", "linear-regression"],
    },
    "data-manipulation": {
        "commands": ["gcollapse", "gegen", "greshape"],
        "source_topics": ["gtools"],
        "install_commands": ["ssc install gtools, replace"],
        "smoke_test": "sysuse auto, clear\ngcollapse (mean) price mpg, by(foreign)",
        "related_refs": ["data-management", "workflow-best-practices"],
    },
    "diagnostics": {
        "commands": ["estat vif", "ovtest", "linktest", "rvfplot"],
        "source_topics": ["regress_postestimation"],
        "install_commands": [],
        "smoke_test": "sysuse auto, clear\nreg price mpg weight\nestat vif",
        "related_refs": ["linear-regression", "graphics"],
    },
    "did": {
        "commands": ["csdid"],
        "source_topics": ["csdid"],
        "install_commands": ["ssc install csdid, replace"],
        "smoke_test": "clear\nset obs 80\ngen id = ceil(_n/4)\ngen t = mod(_n-1,4)\ngen gvar = cond(id <= 10, 2, 0)\ngen y = rnormal() + 2*(gvar>0 & t>=gvar)\ncsdid y, ivar(id) time(t) gvar(gvar) notyet",
        "related_refs": ["difference-in-differences", "treatment-effects"],
    },
    "estout": {
        "commands": ["eststo", "esttab", "estout"],
        "source_topics": ["estout"],
        "install_commands": ["ssc install estout, replace"],
        "smoke_test": "sysuse auto, clear\neststo clear\neststo: reg price mpg weight\nesttab",
        "related_refs": ["tables-reporting", "outreg2"],
    },
    "event-study": {
        "commands": ["eventstudyinteract"],
        "source_topics": ["eventstudyinteract"],
        "install_commands": [
            'net install require, from("https://raw.githubusercontent.com/sergiocorreia/stata-require/master/src/") replace',
            'net install ftools, from("https://raw.githubusercontent.com/sergiocorreia/ftools/master/src/") replace',
            "ftools, compile",
            "mata: mata mlib index",
            'net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/") replace',
            "capture noisily reghdfe, compile",
            "ssc install avar, replace",
            "ssc install eventstudyinteract, replace",
        ],
        "smoke_test": "webuse nlswork, clear\nkeep if inrange(year, 70, 82)\ngen union_year = year if union == 1\nbysort idcode: egen first_union = min(union_year)\ndrop union_year\ngen ry = year - first_union\ngen never_union = first_union == .\nforvalues k = 3(-1)2 {\n    gen g_`k' = ry == -`k'\n}\ngen g0 = ry == 0\nforvalues k = 1/2 {\n    gen g`k' = ry == `k'\n}\neventstudyinteract ln_wage g_3 g_2 g0 g1 g2, cohort(first_union) control_cohort(never_union) covariates(south) absorb(idcode year) vce(cluster idcode)",
        "related_refs": ["difference-in-differences", "graphics"],
    },
    "graph-schemes": {
        "commands": ["grstyle", "set scheme"],
        "source_topics": ["grstyle"],
        "install_commands": ["ssc install grstyle, replace"],
        "smoke_test": "grstyle init",
        "related_refs": ["graphics", "tables-reporting"],
    },
    "ivreg2": {
        "commands": ["ivreg2"],
        "source_topics": ["ivreg2"],
        "install_commands": ["ssc install ranktest, replace", "ssc install ivreg2, replace"],
        "smoke_test": "sysuse auto, clear\ngen z = turn + trunk\nivreg2 price weight (mpg = z)",
        "related_refs": ["linear-regression", "gmm-estimation"],
    },
    "nprobust": {
        "commands": ["lprobust", "lpbwselect", "kdrobust", "kdbwselect"],
        "source_topics": ["nprobust"],
        "install_commands": [
            'net install nprobust, from("https://raw.githubusercontent.com/nppackages/nprobust/master/stata") replace'
        ],
        "smoke_test": "sysuse auto, clear\nlprobust price mpg",
        "related_refs": ["nonparametric-methods", "graphics"],
    },
    "outreg2": {
        "commands": ["outreg2"],
        "source_topics": ["outreg2"],
        "install_commands": ["ssc install outreg2, replace"],
        "smoke_test": "sysuse auto, clear\nreg price mpg weight\noutreg2 using outreg2_smoke.doc, replace",
        "related_refs": ["tables-reporting", "estout"],
    },
    "package-management": {
        "commands": ["search", "ssc install", "net install", "adoupdate"],
        "source_topics": ["search", "ssc", "net", "adoupdate"],
        "install_commands": [],
        "smoke_test": "search reghdfe",
        "related_refs": ["workflow-best-practices", "external-tools-integration"],
    },
    "psmatch2": {
        "commands": ["psmatch2"],
        "source_topics": ["psmatch2"],
        "install_commands": ["ssc install psmatch2, replace"],
        "smoke_test": "sysuse auto, clear\ngen treat = foreign\npsmatch2 treat mpg weight, outcome(price) neighbor(1)",
        "related_refs": ["matching-methods", "treatment-effects"],
    },
    "rdrobust": {
        "commands": ["rdrobust"],
        "source_topics": ["rdrobust"],
        "install_commands": ["ssc install rdrobust, replace"],
        "smoke_test": "clear\nset obs 200\ngen x = _n - 100\ngen y = x + 2*(x>=0) + rnormal()\nrdrobust y x",
        "related_refs": ["regression-discontinuity", "graphics"],
    },
    "reghdfe": {
        "commands": ["reghdfe", "ivreghdfe"],
        "source_topics": ["reghdfe", "ivreghdfe"],
        "install_commands": [
            'net install require, from("https://raw.githubusercontent.com/sergiocorreia/stata-require/master/src/") replace',
            'net install ftools, from("https://raw.githubusercontent.com/sergiocorreia/ftools/master/src/") replace',
            "ftools, compile",
            "mata: mata mlib index",
            'net install reghdfe, from("https://raw.githubusercontent.com/sergiocorreia/reghdfe/master/src/") replace',
            "capture noisily reghdfe, compile",
        ],
        "smoke_test": "webuse nlswork, clear\nreghdfe ln_wage tenure ttl_exp, absorb(idcode year)",
        "related_refs": ["linear-regression", "panel-data", "ivreg2"],
    },
    "synth": {
        "commands": ["synth"],
        "source_topics": ["synth"],
        "install_commands": ["ssc install synth, replace"],
        "smoke_test": "clear\nset seed 12345\nset obs 60\ngen state = ceil(_n/10)\nbysort state: gen year = 2000 + _n - 1\ntsset state year\ngen beer = 20 + state + runiform()\ngen lnincome = 10 + 0.02*(year - 2000) + 0.1*state\ngen retprice = 50 + 0.5*state + runiform()\ngen age15to24 = 0.18 + 0.005*runiform()\ngen cigsale = 100 + 2*state + 0.4*(year - 2000) + 1.2*beer - 0.5*retprice + 12*age15to24 + rnormal()\nreplace cigsale = cigsale - 8 if state == 1 & year >= 2006\nsynth cigsale beer(2003(1)2005) lnincome retprice age15to24 cigsale(2005) cigsale(2003) cigsale(2001), trunit(1) trperiod(2006)",
        "related_refs": ["treatment-effects", "graphics"],
    },
    "tabout": {
        "commands": ["tabout"],
        "source_topics": ["tabout"],
        "install_commands": ["ssc install tabout, replace"],
        "smoke_test": "sysuse auto, clear\ntabout foreign using tabout_smoke.txt, c(mean price) replace",
        "related_refs": ["tables-reporting", "graphics"],
    },
    "winsor": {
        "commands": ["winsor2"],
        "source_topics": ["winsor2"],
        "install_commands": ["ssc install winsor2, replace"],
        "smoke_test": "sysuse auto, clear\nwinsor2 price, replace cuts(1 99)",
        "related_refs": ["data-management", "workflow-best-practices"],
    },
    "xtabond2": {
        "commands": ["xtabond2"],
        "source_topics": ["xtabond2"],
        "install_commands": ["ssc install xtabond2, replace"],
        "smoke_test": "webuse abdata, clear\nxtabond2 n L.n w k, gmm(L.n, lag(2 .)) iv(w k) nolevel robust",
        "related_refs": ["panel-data", "gmm-estimation"],
    },
}

PACKAGE_UPSTREAM_ONLY = {
    "asdoc",
    "binsreg",
    "coefplot",
    "data-manipulation",
    "did",
    "estout",
    "event-study",
    "graph-schemes",
    "ivreg2",
    "nprobust",
    "outreg2",
    "psmatch2",
    "rdrobust",
    "reghdfe",
    "synth",
    "tabout",
    "winsor",
    "xtabond2",
}

PLUGIN_SECTIONS = {
    "SDK and Entry Points": ["plugin-sdk-basics"],
    "C++ Wrapping": ["cpp_plugins"],
    "Packaging and Distribution": ["packaging_and_help"],
    "Performance Patterns": ["performance_patterns"],
    "Testing and Validation": ["testing_strategy"],
    "Translation Workflow": ["translation_workflow"],
}

PLUGIN_METADATA = {
    "plugin-sdk-basics": {
        "title": "Plugin SDK Basics",
        "commands": ["program ..., plugin", "plugin"],
        "source_topics": ["plugin"],
        "upstream_relpath": None,
        "related_refs": ["cpp_plugins", "packaging_and_help"],
        "validation_case": "Compile a minimal plugin and load it with program ..., plugin using(path/to/plugin).",
        "allow_upstream_only": False,
    },
    "cpp_plugins": {
        "commands": ["extern \"C\"", "stata_call", "SF_vdata", "SF_vstore"],
        "source_topics": ["plugin"],
        "related_refs": ["plugin-sdk-basics", "performance_patterns"],
        "validation_case": "Wrap a small C++ routine behind stata_call and confirm it returns 0 in batch mode.",
        "allow_upstream_only": True,
    },
    "packaging_and_help": {
        "commands": [".pkg", ".toc", ".sthlp", "net install"],
        "source_topics": ["net", "ssc", "plugin"],
        "related_refs": ["plugin-sdk-basics", "testing_strategy"],
        "validation_case": "Build a tiny package directory with plugin binary, ado, and sthlp, then install it from a local folder.",
        "allow_upstream_only": True,
    },
    "performance_patterns": {
        "commands": ["pthreads", "presort", "buffer reuse"],
        "source_topics": ["plugin"],
        "related_refs": ["cpp_plugins", "testing_strategy"],
        "validation_case": "Compare a simple plugin baseline against a version that reduces repeated passes over the data.",
        "allow_upstream_only": True,
    },
    "testing_strategy": {
        "commands": ["batch smoke tests", "correlation checks", "return codes"],
        "source_topics": ["plugin", "runtest"],
        "related_refs": ["plugin-sdk-basics", "translation_workflow"],
        "validation_case": "Run plugin smoke tests in batch mode and fail the test if the log contains r() errors.",
        "allow_upstream_only": True,
    },
    "translation_workflow": {
        "commands": ["inventory", "wrap existing backend", "fidelity audit"],
        "source_topics": ["plugin"],
        "related_refs": ["cpp_plugins", "testing_strategy"],
        "validation_case": "Start from an existing Python or R package and document the translation plan before coding.",
        "allow_upstream_only": True,
    },
}


def section_for(slug: str, mapping: dict[str, list[str]]) -> str:
    for section, slugs in mapping.items():
        if slug in slugs:
            return section
    raise KeyError(f"Missing section mapping for {slug}")
